### PR TITLE
Added ogg voice files during pause and restart of game.

### PR DESCRIPTION
**Pull request by SubhradeepSS**

### CODE REVIEW

**Comment by SubhradeepSS** [comment]
Added mp3 voice files during pause and restart of game for Issue #2 
@bvishal8510  Please review.

**Comment by bvishal8510** [comment]
@SubhradeepSS please convert the sounds into ogg format and try to use a more computerized voice instead of these voices.

**Comment by bvishal8510** [comment]
After this squash your commits into one.

**Comment by SubhradeepSS** [comment]
> @SubhradeepSS please convert the sounds into ogg format and try to use a more computerized voice instead of these voices.

@bvishal8510 can u please help me where to get computerized voices?I searched but didn't get specific voices.

**Comment by bvishal8510** [comment]
> > @SubhradeepSS please convert the sounds into ogg format and try to use a more computerized voice instead of these voices.
> 
> @bvishal8510 can u please help me where to get computerized voices?I searched but didn't get specific voices.

@SubhradeepSS sure, let me also search for the voices I am looking for.

**Comment by SubhradeepSS** [comment]
> After this squash your commits into one.

@bvishal8510  Converted mp3 files to ogg files and squashed the commits.

**Pull request merged**
